#!/usr/bin/env bash
set -euo pipefail

# Configuration
BUILD_TYPE="${BUILD_TYPE:-debug}"        # "release" or "debug"
OUTPUT_DIR="${OUTPUT_DIR:-/output}"
VERSION_NAME="${VERSION_NAME:-0.0.0}"

# Suppress Expo telemetry and interactive prompts
export EXPO_NO_TELEMETRY=1
export CI=true

echo "==> MulsikMul APK build -- type=${BUILD_TYPE}, version=${VERSION_NAME}"
node --version
java -version

# Expo prebuild
# --no-install: node_modules already present (mounted from host)
# --clean: ensure a fresh android/ directory
echo "==> expo prebuild --platform android --no-install --clean"
npx expo prebuild --platform android --no-install --clean

# Release signing config
if [ "${BUILD_TYPE}" = "release" ]; then
  echo "==> Configuring release signing"

  if [ -z "${KEYSTORE_PATH:-}" ] || [ ! -f "${KEYSTORE_PATH}" ]; then
    echo "ERROR: KEYSTORE_PATH is not set or file does not exist: '${KEYSTORE_PATH:-}'" >&2
    exit 1
  fi

  # Append signing credentials to gradle.properties (generated by prebuild)
  # These are read by the patched signingConfigs block in app/build.gradle
  cat >> android/gradle.properties <<EOF

MULSIKMUL_UPLOAD_STORE_FILE=${KEYSTORE_PATH}
MULSIKMUL_UPLOAD_STORE_PASSWORD=${STORE_PASSWORD}
MULSIKMUL_UPLOAD_KEY_ALIAS=${KEY_ALIAS}
MULSIKMUL_UPLOAD_KEY_PASSWORD=${KEY_PASSWORD}
EOF

  # Patch android/app/build.gradle to add the release signingConfig block
  python3 /patch-signing.py android/app/build.gradle
fi

# Gradle build
cd android
chmod +x gradlew

if [ "${BUILD_TYPE}" = "release" ]; then
  GRADLE_TARGET="assembleRelease"
  APK_SRC="app/build/outputs/apk/release/app-release.apk"
else
  GRADLE_TARGET="assembleDebug"
  APK_SRC="app/build/outputs/apk/debug/app-debug.apk"
fi

echo "==> ./gradlew ${GRADLE_TARGET}"
./gradlew "${GRADLE_TARGET}" \
  --no-daemon \
  --stacktrace

# Copy output
mkdir -p "${OUTPUT_DIR}"
FINAL_APK="${OUTPUT_DIR}/mulsikmul-${VERSION_NAME}.apk"
cp "${APK_SRC}" "${FINAL_APK}"

echo "==> Done: ${FINAL_APK}"
ls -lh "${FINAL_APK}"
