#!/usr/bin/env python3
"""
Patches android/app/build.gradle (generated by expo prebuild) to add a
release signingConfig block that reads credentials from gradle.properties.

expo prebuild (Expo SDK 55 / config-plugins) generates a signingConfigs { debug { ... } }
block but leaves the release config absent or empty. This script inserts the
release block after the debug block so assembleRelease picks it up.
"""
import sys
import re

if len(sys.argv) < 2:
    print("Usage: patch-signing.py <path/to/build.gradle>", file=sys.stderr)
    sys.exit(1)

path = sys.argv[1]

with open(path, "r") as f:
    content = f.read()

RELEASE_BLOCK = """        release {
            if (project.hasProperty('MULSIKMUL_UPLOAD_STORE_FILE')) {
                storeFile file(MULSIKMUL_UPLOAD_STORE_FILE)
                storePassword MULSIKMUL_UPLOAD_STORE_PASSWORD
                keyAlias MULSIKMUL_UPLOAD_KEY_ALIAS
                keyPassword MULSIKMUL_UPLOAD_KEY_PASSWORD
            }
        }"""

# Check if a release signingConfig block already exists
if re.search(r'signingConfigs\s*\{[^}]*release\s*\{', content, re.DOTALL):
    print(f"Release signingConfig already present in {path}, replacing content")
    patched = re.sub(
        r'(signingConfigs\s*\{[^}]*?)(release\s*\{[^}]*?\})',
        lambda m: m.group(1) + RELEASE_BLOCK,
        content,
        flags=re.DOTALL,
    )
else:
    # Insert release block after the debug block inside signingConfigs { ... }
    patched = re.sub(
        r'(signingConfigs\s*\{[^}]*?debug\s*\{[^}]*?\})',
        r'\1\n' + RELEASE_BLOCK,
        content,
        flags=re.DOTALL,
    )

if patched == content:
    print(f"WARNING: Could not locate signingConfigs debug block in {path}. "
          "Signing may not be configured correctly.", file=sys.stderr)
    sys.exit(1)

with open(path, "w") as f:
    f.write(patched)

print(f"Patched release signingConfig in {path}")
